# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 15:19
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stravaChimp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='df',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
