# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stravaChimp', '0002_activity_df'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='totalDist',
            field=models.FloatField(default=0.0, max_length=50),
        ),
    ]
