# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 15:38
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stravaChimp', '0006_auto_20160327_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='act_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='avgHr',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='df',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='easy',
            field=models.FloatField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='hrVar',
            field=models.FloatField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='impulse',
            field=models.FloatField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='realMiles',
            field=models.FloatField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='recovery',
            field=models.FloatField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='stamina',
            field=models.FloatField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='totalDist',
            field=models.FloatField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='totalTime',
            field=models.FloatField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='athleteId',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
