# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stravaChimp', '0007_auto_20160327_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='act_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='climb',
            field=models.FloatField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='followers',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='friends',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='meas_pref',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='premium',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='athlete',
            name='profilePic',
            field=models.ImageField(null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='athlete',
            name='sex',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='weight',
            field=models.FloatField(max_length=50, null=True),
        ),
    ]
