# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stravaChimp', '0008_auto_20160327_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='timezone',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
