# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 21:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stravaChimp', '0011_auto_20160327_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='athlete',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stravaChimp.Athlete'),
        ),
    ]
