# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 03:17
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stravaChimp', '0012_activity_athlete'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='fitline',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
