# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 21:27
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stravaChimp', '0013_activity_fitline'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='fitlines',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
