# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 21:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stravaChimp', '0014_athlete_fitlines'),
    ]

    operations = [
        migrations.RenameField(
            model_name='athlete',
            old_name='fitlines',
            new_name='fitLines',
        ),
    ]
