# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-14 20:41
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stravaChimp', '0015_auto_20160410_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='masterList',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
