# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-21 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stravaChimp', '0016_athlete_masterlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='mafScore',
            field=models.FloatField(max_length=50, null=True),
        ),
    ]
