# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-28 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stravaChimp', '0017_activity_mafscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='profilePic',
            field=models.ImageField(null=True, upload_to=b'profile_pics'),
        ),
    ]
