# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-01 19:13
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stravaChimp', '0018_auto_20160628_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='mafLastFive',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
